site_name: Тестовая документация Mkdocs
site_description: Тeстовый сайт документации на Mkdocs
theme: material
nav:
  - Главная:
      - Справочник API: dist/index.html
      - Основные положения: main_info.md
      - Инструменты и сценарии: tools.md
      - Начало работы: get_start.md
      - Готовые решения: example.md
  - Статьи: articles.md
  - Новости: news.md
